services:
  postgresdb:
    container_name: statemachine.db
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=statemachine
      - POSTGRES_PASSWORD=statemachine
      - POSTGRES_DB=statemachine
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432