spring:
  application:
    name: lot-state-poc
  autoconfigure:
    # Excluded from autoconfiguration because we use our own datasource
    exclude: org.springframework.statemachine.boot.autoconfigure.StateMachineJpaRepositoriesAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
# Default application datasource (can be another DB not the same with State machine)
audax:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/statemachine
    username: statemachine
    password: statemachine
# State machine datasource
statemachine:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/statemachine
    username: statemachine
    password: statemachine

logging.level.org.springframework.statemachine: DEBUG