package com.audax.state.machine.event;

public enum OrderEvent {
	PROCESS_ORDER,
	SHIPPING_START,
	SHIPPING_LABEL_CREATED,
	SHIPPING_DONE,
	DELIVERY_START,
	DELIVERY_LABEL_CREATED,
	DELIVERY_DONE,
	CANCEL_ORDER
}